CU=nvcc
CUFLAGS=-O2 -Xcompiler=-Wall -Xcompiler=-Wextra
LDFLAGS=

TARGETS=tiny_mc_shared_prng_cpu

all: $(TARGETS)

tiny_mc_shared_prng_cpu: tiny_mc_shared_prng_cpu.o
	$(CU) $(CUFLAGS) -o $@ $^ $(LDFLAGS)

# CU, CUFLAGS no tienen regla implicita como CC/CFLAGS
%.o: %.cu
	$(CU) $(CUFLAGS) -o $@ -c $<

.PHONY: clean

clean:
	rm -f *.o $(TARGETS)
